//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.RegistroTransacciones = new HashSet<RegistroTransacciones>();
        }
    
        public int Id_Empleado { get; set; }
        public string Cedula_Empleado { get; set; }
        public string Nombre_Empleado { get; set; }
        public string Apellido_Empleado { get; set; }
        public string Sexo_Empleado { get; set; }
        public string Direccion_Empleado { get; set; }
        public string Telefono_Empleado { get; set; }
        public string TelefonoE_Empleado { get; set; }
        public string Nacionalidad_Empleado { get; set; }
        public string EstadoCivil_Empleado { get; set; }
        public Nullable<int> CantidadHijos_Empleado { get; set; }
        public Nullable<int> Id_Departamento { get; set; }
        public Nullable<int> Id_Puesto { get; set; }
        public Nullable<decimal> SalarioMensual_Empleado { get; set; }
        public Nullable<int> Id_TipoNomina { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Puestos Puestos { get; set; }
        public virtual TiposNominas TiposNominas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroTransacciones> RegistroTransacciones { get; set; }
    }
}
