//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroller
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayrollerEntities : DbContext
    {
        public PayrollerEntities()
            : base("name=PayrollerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<NivelesRiesgo> NivelesRiesgo { get; set; }
        public virtual DbSet<Puestos> Puestos { get; set; }
        public virtual DbSet<RegistroTransacciones> RegistroTransacciones { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TiposDeducciones> TiposDeducciones { get; set; }
        public virtual DbSet<TiposIngresos> TiposIngresos { get; set; }
        public virtual DbSet<TiposNominas> TiposNominas { get; set; }
    }
}
