//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroller
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposIngresos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposIngresos()
        {
            this.RegistroTransacciones = new HashSet<RegistroTransacciones>();
        }
    
        public int Id_TipoIngreso { get; set; }
        public string Nombre_TipoIngreso { get; set; }
        public string DependeSalario_TipoIngreso { get; set; }
        public string Estado_TipoIngreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroTransacciones> RegistroTransacciones { get; set; }
    }
}
